name: "[CI] Continuous Integration"

# Sempre que um commit ou PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        ## [COmmon_CI_STEPS]
        - uses: actions/checkout@v3
        ## ========
        - name: "Debug"
          run: "ls -la"
        - name: "Install Dependecies"
          run: "npm install"
        - name: "Lint"
          run: "npm run lint"
