name: "[CI] Continuous Integration"

# Sempre que um commit ou PR for aberto
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint"
        run: "echo 'alo alo w brasil'"
