name: "[CI] Continuous Delivery"

# Sempre que um commit ou PR for aberto

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [COmmon_CI_STEPS]
      - uses: actions/checkout@v3
      ## ========
      - name: "Debug"
        run: "ls -la"
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Lint"
        run: "npx vercel --prod --token=ZolxVyhDPVTDIvkbvoZB5xdu"

